CREATE TABLE Channel (
ChannelID INT PRIMARY KEY,
Name VARCHAR(150) NOT NULL,
SubCount INT DEFAULT 0,
CreationDate DATETIME NOT NULL
);

SELECT *
FROM Channel;

CREATE TABLE Video (
VideoID INT PRIMARY KEY,
Name VARCHAR(150) NOT NULL,
Views INT DEFAULT 0,
Likes INT DEFAULT 0,
Dislikes INT DEFAULT 0,
Duration INT NOT NULL,
ChannelID INT FOREIGN KEY REFERENCES Channel(ChannelID)
);

SELECT *
FROM Video;

CREATE TABLE Home (
HomeID INT PRIMARY KEY,
Residents INT DEFAULT 1,
Room VARCHAR(150) NOT NULL,
Floor INT DEFAULT 1
);

SELECT *
FROM Home;

CREATE TABLE Room(
RoomID INT PRIMARY KEY,
Furniture VARCHAR(150) NOT NULL,
HomeID INT FOREIGN KEY REFERENCES Home(HomeID)
);

SELECT *
FROM Room;